export enum Role {
  DIRECTOR = "DIRECTOR",
  MANAGER_FINANCIAL = "MANAGER_FINANCIAL",
  MANAGER_FLEET = "MANAGER_FLEET",
  MANAGER_ONSITE = "MANAGER_ONSITE",
  MANAGER_RECRUITMENT = "MANAGER_RECRUITMENT",
  DRIVER = "DRIVER",
}
